# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "Biapy Hugo Theme"
license = "MIT"
licenselink = "Link to theme's license"
description = "Theme description"

# The home page of the theme, where the source can be found.
homepage = "https://github.com/biapy/biapy-hugo-theme"

# If you have a running demo of the theme.
# demosite = "https://gohugo.io"

tags = ["blog", "biapy"]
features = ["tailwind"]

# If the theme has a single author
[author]
    name = "Pierre-Yves LANDURÉ"
    homepage = "https://howto.biapy.com/"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.101.0"
